DAHDI: Fix compiling on 32-bit by disabling XPP drivers.
Commit 6cedcea94a8290faf232778188db826ff53d86f8
previously disabled building the XPP drivers
on 32-bit ARM. However, these same issues exist
with any 32-bit architecture, e.g. i686:

MODPOST /usr/src/dahdi-linux-3.2.0/drivers/dahdi/Module.symvers
ERROR: modpost: "__divdi3" [/usr/src/dahdi-linux-3.2.0/drivers/dahdi/xpp/xpp_usb.ko] undefined!
ERROR: modpost: "__udivdi3" [/usr/src/dahdi-linux-3.2.0/drivers/dahdi/xpp/xpp_usb.ko] undefined!
ERROR: modpost: "__moddi3" [/usr/src/dahdi-linux-3.2.0/drivers/dahdi/xpp/xpp.ko] undefined!
ERROR: modpost: "__divdi3" [/usr/src/dahdi-linux-3.2.0/drivers/dahdi/xpp/xpp.ko] undefined!
make[3]: *** [/usr/src/linux-headers-5.10.0-21-common/scripts/Makefile.modpost:123: /usr/src/dahdi-linux-3.2.0/drivers/dahdi/Module.symvers] Error 1

This is not actually a fix for the issue above, but it
disables building the XPP drivers so that compilation
will succeed on 32-bit platforms, since neither 32-bit
nor the XPP drivers are widely used. A more direct fix
is certainly welcome in the future.

Fixes #12