patches: Fix condition in dahdicleanup.diff.
In dahdi_handle_event, the variable 'x' was, in the original iteration
of this patch, guarded by !defined(SIG_ANALOG_HANDLED), but on systems
with libpri, this would cause compilation failure:

chan_dahdi.c: In function 'dahdi_handle_event':
chan_dahdi.c:7966:68: error: 'x' undeclared (first use in this function)
 7966 | if (ioctl(p->subs[idx].dfd, DAHDI_DIALING, &x) == -1) {

This was thus not guarded by a define at all, which usually works,
except this can also cause compilation failure when libpri is not present:

chan_dahdi.c: In function 'dahdi_handle_event':
chan_dahdi.c:7840:18: error: unused variable 'x' [-Werror=unused-variable]
 7840 | int res, x;

The proper condition for when x needs to exist is when either SIG_ANALOG_HANDLED
is not defined (i.e. the original code, where duplicate analog handling code
would use x) or when HAVE_PRI is defined, since this code is not dead and also
uses x. The warning about unused variable would happen only when HAVE_PRI
was not defined, and thus with the dead code not being compiled, x would not
see any usage.

PHREAKSCRIPT-63 #close